In [1]:
from __future__ import print_function

import cv2
import PIL
from PIL import Image
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.optimizers import Adadelta
from keras.utils import np_utils
from keras.regularizers import l2 #, activity_l2
import numpy as np
#import cPickle 
import numpy
import cv2
import scipy
import csv
from __future__ import print_function
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.optimizers import Adadelta
from keras.utils import np_utils
from keras.regularizers import l2  #, activity_l2
import _pickle as cPickle 
import numpy
import csv
import scipy.misc
import scipy
from scipy import ndimage
import imutils
import cv2
import numpy as np
from keras.preprocessing.image import ImageDataGenerator
from keras.models import load_model


/opt/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
mnew_model = load_model('model6_total_#4set_kwang.hdf5')

In [ ]:
mnew_model.summary()

In [3]:
import os
from keras.preprocessing.image import ImageDataGenerator, load_img
from keras.utils import to_categorical
def createFileList(myDir):
    format = ('.tiff','.jpg','.png','.PNG')
    fileList = []
    print(os.walk(myDir, topdown=False))
    for root, dirs, files in os.walk(myDir, topdown=False):
        
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList 

In [4]:
test_x , test_y = [],[]

In [5]:
fileList = []
fileList = createFileList('./data/valid')

<generator object walk at 0x7f126c1bbf68>


In [6]:
print(fileList[:10])

['./data/valid/sad/S052_002_00000019.png', './data/valid/sad/S035_002_00000007.png', './data/valid/sad/S037_002_00000014.png', './data/valid/sad/S052_002_00000017.png', './data/valid/sad/S046_001_00000019.png', './data/valid/sad/NA.SA1.205.tiff', './data/valid/sad/S051_003_00000008.png', './data/valid/sad/S014_002_00000013.png', './data/valid/sad/22.PNG', './data/valid/sad/S055_004_00000028.png']


In [8]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

classes={0:'angry', 1:'fear', 2:'happy', 3:'neutral', 4:'sad', 5:'surprise'}


for i in classes.items():
    print(i)

(0, 'angry')
(1, 'fear')
(2, 'happy')
(3, 'neutral')
(4, 'sad')
(5, 'surprise')


In [9]:



for x in fileList:
    z = load_img(path =x, grayscale=True, target_size=(227,227),
    interpolation='nearest')
    q=np.asarray(z).astype('float32')
    q = np.asarray([q])
    test_x.append(q)
    
    t = -1
    for y in classes.items():
        if y[1] in x:
            t = y[0]
        
    test_y.append(to_categorical(t, 6))

test_x = np.asarray(test_x)
test_x1=np.moveaxis(test_x, 1, 3)
test_y = np.asarray(test_y)
print(test_x1)   
print(test_y)

[[[[ 91.]
   [ 90.]
   [ 88.]
   ...
   [ 79.]
   [ 82.]
   [ 83.]]

  [[ 91.]
   [ 89.]
   [ 87.]
   ...
   [ 73.]
   [ 75.]
   [ 78.]]

  [[ 88.]
   [ 85.]
   [ 85.]
   ...
   [ 68.]
   [ 71.]
   [ 74.]]

  ...

  [[ 69.]
   [ 71.]
   [ 80.]
   ...
   [ 61.]
   [ 68.]
   [ 71.]]

  [[ 72.]
   [ 74.]
   [ 78.]
   ...
   [ 65.]
   [ 63.]
   [ 63.]]

  [[ 68.]
   [ 70.]
   [ 69.]
   ...
   [ 65.]
   [ 63.]
   [ 63.]]]


 [[[154.]
   [157.]
   [155.]
   ...
   [164.]
   [164.]
   [164.]]

  [[154.]
   [157.]
   [155.]
   ...
   [167.]
   [167.]
   [167.]]

  [[154.]
   [151.]
   [149.]
   ...
   [166.]
   [166.]
   [167.]]

  ...

  [[139.]
   [141.]
   [142.]
   ...
   [ 24.]
   [ 25.]
   [ 25.]]

  [[139.]
   [138.]
   [139.]
   ...
   [ 29.]
   [ 29.]
   [ 39.]]

  [[137.]
   [137.]
   [138.]
   ...
   [ 31.]
   [ 31.]
   [ 30.]]]


 [[[189.]
   [190.]
   [191.]
   ...
   [179.]
   [186.]
   [188.]]

  [[186.]
   [187.]
   [189.]
   ...
   [181.]
   [189.]
   [187.]]

  [[191.]
   [18

In [ ]:
print(test_y[:100]) 

In [ ]:
test_x1.shape

In [ ]:
temp = np.array([test_x1[0]])
temp.shape

In [ ]:
temp_show=np.moveaxis(np.moveaxis(temp[0].astype('float32'), 0, 2),0,2)
temp_show.shape
plt.imshow(temp_show[0],cmap='gray')

In [ ]:
prediction_score = mnew_model.predict_proba(q, batch_size = 1)
np.argmax(prediction_score)

In [ ]:
temp.shape
#q=np.moveaxis(np.moveaxis(temp, 1,3),1,3)
#print(q.shape)
q=np.moveaxis(temp, 1,2)



In [ ]:
temp_show=np.moveaxis(np.moveaxis(q[0], 0, 2),0,2)
temp_show.shape
plt.imshow(temp_show[0],cmap='gray')

In [ ]:
prediction_score = mnew_model.predict_proba(q, batch_size = 1)
np.argmax(prediction_score)

In [ ]:
fig=plt.figure(figsize=(20, 20))
for i in range(50):
    image_to_show=np.moveaxis(np.moveaxis(test_x1[i], 0, 2),0,2)
    fig.add_subplot(10,5,i+1)
    plt.imshow(image_to_show[0],cmap='gray')
    print(np.argmax(mnew_model.predict_proba(test_x1, batch_size = 199)[i]))
    print(mnew_model.predict_proba(test_x1, batch_size = 199)[i])
    print(np.max(mnew_model.predict_proba(test_x1, batch_size = 199)[i]))
    print(test_y[i])
plt.show()
    


In [ ]:
mnew_model.test_on_batch(test_x1, test_y)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
test_x1[0].shape

In [ ]:
image_to_show=np.moveaxis(np.moveaxis(test_x1[0], 0, 2),0,2)

In [ ]:
image_to_show.shape

In [ ]:
plt.imshow(image_to_show[0],cmap='gray')

In [ ]:
#mnew_model.metrics_names
print(np.argmax(mnew_model.predict_proba(test_x1, batch_size = 10)[0]))
print(mnew_model.predict_proba(test_x1, batch_size = 10)[0])
print(np.max(mnew_model.predict_proba(test_x1, batch_size = 10)[0]))

In [ ]:
image_to_show=np.moveaxis(np.moveaxis(test_x1[3], 0, 2),0,2)
plt.imshow(image_to_show[0],cmap='gray')
print(np.argmax(mnew_model.predict_proba(test_x1, batch_size = 10)[4]))
print(mnew_model.predict_proba(test_x1, batch_size = 10)[3])
print(np.max(mnew_model.predict_proba(test_x1, batch_size = 10)[3]))

In [ ]:
proba = predict_prob(0,test_set_x,model)kera
proba1 = predict_prob(1,test_set_x,model)
proba2 = predict_prob(2,test_set_x,model)
proba3 = predict_prob(3,test_set_x,model)
proba4 = predict_prob(4,test_set_x,model)
proba5 = predict_prob(5,test_set_x,model)
proba6 = predict_prob(6,test_set_x,model)
proba7 = predict_prob(7,test_set_x,model)
Out = []
for row in zip(proba,proba1,proba2,proba3,proba4,proba5,proba6,proba7):
	a = numpy.argmax(np.array(row).mean(axis=0))
	Out.append(a)

Out = np.array(Out)
test_set_y = np.array(test_set_y)
c = np.sum(Out == test_set_y)
print("Acc:"+str((float(c)/len(Out))))